### ISSUE TITLE
Provide performance analytics

### ISSUE THREAD

**Issue by SandWoodJones** [emilyploszaj/emi#12]
REI has a handy button that gives you a performance analysis in ms for each REI function such as entry registration and displaying.
It's useful as you can easily find what mod is causing REI to stutter.
If EMI also provided these numbers modpack creators could easily compare the performance of the 2 mods and choose the one that fits best to the modpack.

**Comment by emilyploszaj** [comment]
EMI currently logs performance statistics fort he total registration time of a mod. For instance, on my computer in a dev environment, I get a print similar to `[emi] Reloaded plugin from EMI in 187ms` telling me that the vanilla integration for EMI took 187ms. EMI doesn't have a more thorough breakdown for this because EMI's registration happens all at once. And of course, the performance of these loads only happen whenever joining a game or when the world reloads, and occurs off thread, so will very rarely actually have an impact on players. I'm curious what more detailed information you'd prefer to have displayed?

**Comment by SandWoodJones** [comment]
Here's an example, running Another Quality Modpack 2
![image](https://user-images.githubusercontent.com/35671374/173690696-a27360a2-5397-4f4b-8ea6-8ee5cf684429.png)
![image](https://user-images.githubusercontent.com/35671374/173690742-ce756198-eaf9-4405-8162-6fe2e3c82b6f.png)
With this I know that most of the lag comes from displaying items from the create mod

**Comment by emilyploszaj** [comment]
Ah, this is the same type of info that EMI provides in the log. These numbers are *load time*, not render time. The high number does not indicate that create is creating a lot of lag rendering items, it is indicating that, when you join a world, it takes 3.485 seconds for create to initialize all of its recipes.

**Comment by SandWoodJones** [comment]
I see then. Thanks for clarifying
