### ISSUE TITLE
[BUG] Enabling "cheat mode" doesn't appear to do anything

### ISSUE THREAD

**Issue by Sollace** [emilyploszaj/emi#172]
Tried turning on cheat mode in a singleplayer world. Testing in survival and creative, but dragging items from the emi panel into the inventory does not appear to do anything.

I assume you're supposed to give yourself items from the panel with this option enabled (similar to how TMI, JEI, NEI worked)?

**Comment by fzzyhmstrs** [comment]
CTRL+Left/Right click to give yourself stuff in cheat mode

**Comment by emilyploszaj** [comment]
Correct, EMI has rebindable controls for cheating in stacks, cheat mode just enables the ability to use this. They can be rebound to be layered on top of normal mouse buttons if preferred.

**Comment by Sollace** [comment]
Ah, thank you! I'll try the keybinds later.

I still have the question of why clicking and dragging stacks doesn't work though?

**Comment by peow** [comment]
> I still have the question of why clicking and dragging stacks doesn't work though?


sorry for commenting on such an old post, but I also have the same question, why doesn't dragging the item to the inventory work?

**Comment by emilyploszaj** [comment]
It's simply not a feature

**Comment by Sollace** [comment]
I'll note that it's very strange that you _can_ drag things from the item panel. You just can't drop them into the inventory.

Why have that at all if there's no purpose to it?

**Comment by Abbie5** [comment]
some mods use the dragged "fake" stack for eg. setting item filters

**Comment by Sollace** [comment]
> some mods use the dragged "fake" stack for eg. setting item filters

Okay? But I'm talking in terms of EMI and the vanilla inventory. Is it so hard to put the dragged stack into the empty slot your mouse is over when you release the left mouse button?

**Comment by Sollace** [comment]
Ctrl+Left-Click is lame. It only gives you a full stack and you have no control over where it puts it.

Please add drag and drop. Doing so would give EMI a massive advantage over other mods -Items mods and I wouldn't have to keep going back to the regular creative inventory for giving myself items.

**Comment by LucilleTea** [comment]
> I'll note that it's very strange that you _can_ drag things from the item panel. You just can't drop them into the inventory.
> 
> Why have that at all if there's no purpose to it?

Dragging items is also used to set favourites, and if you have multiple favourites pages/sidebars, this is the way to choose which one your favourite is placed in. So alongside setting modded filters, it has at least 2 purposes.

Not to invalidate the feature request, it still seems convenient if possible, and reduces reliance on remembering so many hotkeys? Since mods can assign their own behaviour to the drag it seems like it could cause clashes though.

**Comment by allanonmage** [comment]
It's not particularly obvious that you need a keybind for this. I had this same problem when beta testing my modpack and using EMI for the first time. The arguments on both sides make sense, and I'm guessing it's a minority of people affected by it.

What about a tooltip explaining this in the EMI settings page? That would have been enough for me, since tooltips there are appropriate to explain how things work.
