### ISSUE TITLE
With EMI installed, some tooltips don't properly wrap their text

### ISSUE THREAD

**Issue by aaronhowser1** [emilyploszaj/emi#184]
Without EMI
![image](https://github.com/emilyploszaj/emi/assets/15698722/b6380c4e-0c9b-4f97-968d-587260d4a665)

With EMI
![image](https://github.com/emilyploszaj/emi/assets/15698722/169744d1-b6e0-485c-addb-5889ac23a8a6)

emi-1.0.0+1.19.2+forge

**Comment by emilyploszaj** [comment]
This is an interesting issue, EMI tooltips use raw tooltip components which occur a level after Forge tooltip wrapping, and it is supposed to have its own logic to handle wrapping, I may have adjusted something incorrectly recently and will need to look into it.
It's worth noting this issue is only present inside EMI controlled tooltips, the items themselves will have wrapped tooltips in slots etc.

**Comment by aaronhowser1** [comment]
Is there a config to disable showing in the item tooltip?

**Comment by emilyploszaj** [comment]
Disabling showing what in particular?

Also worth noting that there was a bug specifically with left facing tooltips that was fixed locally and should be pushed with the next release.

**Comment by aaronhowser1** [comment]
Sorry I tried rewording my comment but entirely missed that I also removed the word itself

![image](https://github.com/emilyploszaj/emi/assets/15698722/55ab33e4-2dc9-464b-b204-02748685be11)
The recipe when holding sneak

**Comment by emilyploszaj** [comment]
Oh, yes, showing inferred recipe for usage with the craft binds from the index is controlled a bind in the config, set to shift by default. Unbinding this (or binding it to something you prefer) will prevent it from showing up.

**Comment by emilyploszaj** [comment]
The original text wrapping issue was resolved in 1.0.1
