### ISSUE TITLE
Info pages added by KubeJS are not visible

### ISSUE THREAD

**Issue by aaronhowser1** [emilyploszaj/emi#188]

**Comment by emilyploszaj** [comment]
I'm not able to replicate this with up to date versions of KubeJS, JEI, and EMI. I've not made any changes, so I'm not sure if this bug ever actually existed.
![image](https://github.com/emilyploszaj/emi/assets/14813658/f1295727-b79f-41d7-844e-c0c9352b3462)

It's possible you didn't reload your resources? KubeJS has its JEI stuff in the client scripts so you need to reload resource packs in order for updates to occur, then potentially also reload datapacks. Going to close because I can't replicate, but if I misunderstood let me know and this can be reopened.

**Comment by Kisuny** [comment]
> I'm not able to replicate this with up to date versions of KubeJS, JEI, and EMI. I've not made any changes, so I'm not sure if this bug ever actually existed. 

Have you tested this on a forge?
Because, apparently, it doesn't work at the fabric
![image](https://github.com/emilyploszaj/emi/assets/56004431/3e4bc06e-ded6-4723-9ee0-81bd2367d06a)

And found some info in KubeJS discord:
![image](https://github.com/emilyploszaj/emi/assets/56004431/2ac61ffc-7d38-424f-92b3-de420a471a5a)

**Comment by emilyploszaj** [comment]
Ultimately if kubejs doesn't have JEI events on fabric there's nothing I can do about it, that's out of my reign
