### ISSUE TITLE
[Forge 1.0.1-1.19.2] Items not in creative tabs appearing in index

### ISSUE THREAD

**Issue by BookerCatch** [emilyploszaj/emi#193]
Release version 1.0.0 displayed stacks in the index in the same manner as JEI. The 1.0.1 update made it so now stacks that can't be found in creative tabs. This includes items like Create's incomplete precision mechanism, Supplementaries' bomb projectiles, or again Create's cart contraption item stacks. Was this intended?

**Comment by emilyploszaj** [comment]
This was intended because several mods don't use creative tabs. A more reasonable solution may be to consider mods who display >50% of their items with creative tabs, similar to 1.19.3 and up, and not show the hidden items. If, alternatively most mods add their stacks to creative search and it's accepted standard with JEI, I may revert this change

**Comment by emilyploszaj** [comment]
This was reverted to match JEI and I forgot to close
