### ISSUE TITLE
[Fabric 1.0.1+1.19.2] Startup crash from Bovines and Buttercups

### ISSUE THREAD

**Issue by sisby-folk** [emilyploszaj/emi#198]
[Bovines and Buttercups](https://modrinth.com/mod/bovines-and-buttercups) adds some custom status effects that lock other status effects in place. I'm not sure what it is about the implementation, but EMI 1.0.1 doesn't like it!

https://mclo.gs/MI7bm32

**Comment by emilyploszaj** [comment]
It seems Bovines and Buttercups... injects into EMI's mixins. There's nothing I can do, my mixin changed to support other use cases, you'll have to open a bug on them.

**Comment by ChrysanthCow** [comment]
If you're curious as to why I'm using a mixin, it's because Bovines and Buttercups has an extra tooltip when hovering over the effect inside the menu in survival (as this isn't normal vanilla behaviour to do this), this issue will be fixed when I get to it.

Sorry for the inconvenience. I've realised that this mixin isn't mandatory, and I will remove it.
