### ISSUE TITLE
REI compatible

### ISSUE THREAD

**Issue by KIRUYXAN** [emilyploszaj/emi#255]
Please make it so that he also takes recipes from REI

**Comment by emilyploszaj** [comment]
This is not something EMI plans to implement, sorry.

**Comment by KIRUYXAN** [comment]
Then just add crafts from all mods

**Comment by LemmaEOF** [comment]
That's the responsibility of mods to do, not EMI. The only reason EMI is able to support displaying JEI recipes is because JEI has a specific API that allows recipes to be rendered through EMI, but REI doesn't. Adding REI support would be a *massive* timesink that ultimately wouldn't be worth it, especially with how often REI changes its API.

**Comment by KIRUYXAN** [comment]
Ok, then I will use REI until EMI becomes the best in the world
