### ISSUE TITLE
[1.19.2] Compatibility issue with Simple Storage Network

### ISSUE THREAD

**Issue by ezeTG** [emilyploszaj/emi#273]
Playing a custom modpack I noticed when I tried recipe filling into the Simple Storage Network crafting interface, the items would be misplaced or moved into different positions

I worked my way through the mods and emi ended up being the one causing the issue
Issue still happens with jei and emi alone in a aswell

https://github.com/emilyploszaj/emi/assets/140893028/d9f89a57-448b-403e-b494-17d1f69ec05a

**Comment by Blockmandoo** [comment]
I found the same issue for RFTools Storage's storage scanner, and Integrated Terminals's storage terminal, and be careful because I also discovered its not only failing to place them properly, but also deleting the first item in the crafting grid from your inventory/storage, so odds are decent after this video you are down 1 Diamond, 1 Gold Ingot, and 1 Raw Iron.

**Comment by emilyploszaj** [comment]
While these mods are making mistakes themselves, I've resolved the issue on EMI's side and filling should work as expected.
