### ISSUE TITLE
Odd offset in EMI recipe display

### ISSUE THREAD

**Issue by MuteTiefling** [emilyploszaj/emi#277]
I'm uncertain if this is something we can fix, or if it would need to be fixed in the mod. But in the below screenshot we see that the top recipe does not have the favorite/recipe tree buttons, and so ends up centered. However, the buttons on the second recipe end up pushing the recipe over a bit, causing the two to be misaligned. 

![image](https://github.com/emilyploszaj/emi/assets/9543430/3d7ff555-6cdc-4352-a887-2bbec2bd06b1)

https://github.com/EnigmaticaModpacks/Enigmatica9/issues/597

**Comment by emilyploszaj** [comment]
This is due to the fact that EMI can put the second recipe into the recipe tree, but not the first one (because it has a cycling output), and it doesn't have a way to know if a recipe belongs in the recipe tree because the recipe comes from JEI. AE2 Adding dedicated support specifying their information recipes like this should never go in the recipe tree would solve the issue, but since it's coming from JEI there's not enough information to know what should be done.

**Comment by emilyploszaj** [comment]
It might be viable to have some metadata resource format that disables these buttons on an entire recipe category so modpack makers could fix the weirdness with JEI recipes if they want? But that sounds kinda clunky and I'm not sure if it's a proper solution.

**Comment by emilyploszaj** [comment]
Now that AE2 has first party EMI support I think I'll close this issue, the metadata idea is a bit overcomplicated and ultimately JEMI support will never be *perfect*, in scenarios like this first party EMI support is ideal.
