### ISSUE TITLE
[Feature Request] Smoother compatibility with JEI/Favorite list sharing

### ISSUE THREAD

**Issue by crafting-Aaron** [emilyploszaj/emi#302]
This mod looks amazing and well organized! Only issue I have is that I lose all my favorite recipes I have from JEI when I install this. Is there a way to share the favorite list or transfer it to EMI? When I try to disable EMI on the settings, it still has JEI gone. It would be neat to either toggle between both mods rather than completely disable one.

Some items in the search index also seem to have become darkened? Most blocks and enchanted items such as potion and books have normal brightness but a lot of random things are hard to look at.

**Comment by emilyploszaj** [comment]
Unfortunately JEI's bookmarks and EMI's favorites cannot share with each other, you'll just have to recreate your favorites, but you'll only need to do this once. Sorry :(

In regards to EMI and JEI both being usable at the same time (say if you disable EMI), this isn't possible due to the way that JEI and EMI interact with each other.

If you have shaders they may be breaking batched item rendering. You can disable this (at a performance cost) in the config.

**Comment by crafting-Aaron** [comment]
Yes, I was using a shader and disabling this in your config fixed the brightness problem. Thanks!

**Comment by gentlewatcher** [comment]
I know this is old, but seeing as how the jei emi compat has been implemented well I was hoping this feature request was revisited, seeing as (I have done this in a past playthrough) it is possible to use only regex to do find and replace functions on the json files used it is possible to look for if a jei bookmarks file is present, run regex type functions on it and convert it into emi format, then on later loads check if both files exist and use the latest one, and run the conversion again to backport updates form the most recent file back to the older file thus the mods can be added or removed at any time and your list is shared between both.
