### ISSUE TITLE
When searching tags by default, an option to ignore modname

### ISSUE THREAD

**Issue by Yarden-zamir** [emilyploszaj/emi#342]

**Comment by Yarden-zamir** [comment]
I understand if you don't want to add it but note that it means that ticking the tags by default option means you are also kinda locked into the search mod name by default option without opting into it. Also note that it's not how jei works by default, which is fine, this mod doesn't need to be jei, it's much better, but I would expect at least an option for behavior parity for simple things like search. Thank you either way, your mod is awesome

**Comment by Yarden-zamir** [comment]
I would expect something like so
```java
						String tagWithoutNamespace = EmiTags.getTagName(t).replaceFirst(t.getId().getNamespace()+':','')
						if (pat.matcher(tagWithoutNamespace.toLowerCase()).find()) {
							return true;
						}
```

**Comment by emilyploszaj** [comment]
I closed this because you opened two similar issues in quick succession and this one had no description. The modname in tags is not directly connected to the modname in stacks, so you are not "forced" into using modname search by default, it's just there are a lot of tags. In general search tag by default is an option that exists but I really don't expect anyone to seriously use it. Pack makers should be using aliases, something they have complete control over.
