### ISSUE TITLE
[Request] Sort item tags by mod source and/or alphabetical order.

### ISSUE THREAD

**Issue by PlayfulPiano** [emilyploszaj/emi#351]
Currently when you have any mod that adds many variants of a block type (e.g. chipped), you have to scroll through a huge disorganized list of blocks to favorite specific types for crafting trees. If you could change it such that it is sorted by mod / alphabetical, that would be really beneficial.
e.g. of what I mean (in forge 1.20.1)
![image](https://github.com/emilyploszaj/emi/assets/3158887/edb6f1d6-91b9-4c81-b3d6-297dc175e1ae)

**Comment by emilyploszaj** [comment]
Tags in the tag page are actually sorted by name, but the contents of tags, like all of the planks in the planks tag, are not. Tags themselves are lists, not sets, so they have order that hypothetically matters, especially for pack devs. Lots of tags that have explicit ordering especially in vanilla where alphabetical sorting would make them significantly less appealing. Also, the first item in a tag is particularly important, as it is representative of the rest of the contents. This is working as intended, the weird spammy order of tag entries is caused by the mods adding the content like this, in this case, chipped.

**Comment by PlayfulPiano** [comment]
Ah, so there's no way on your side to at least keep tags separated by the mod that calls them, right? i.e. keeping whatever sorting the mod itself implements for that mod's specific blocks/items, but keep them by order of mod source.
