### ISSUE TITLE
Minor compatibility issue with FTB Quests

### ISSUE THREAD

**Issue by aaronhowser1** [emilyploszaj/emi#366]
So in FTB Quests, if you click on an item it shows you the recipe in JEI. Usually, hitting E from there returns back to the quest you came from:

https://github.com/emilyploszaj/emi/assets/15698722/c2552f7d-f6c2-47d1-ae86-c4070adc064f

But with EMI, instead it goes to the inventory:

https://github.com/emilyploszaj/emi/assets/15698722/6688fa05-0bfd-4441-935f-7592dec4df54

I'm unsure on whose end this would have to be fixed

ftb-quests-forge-1902.5.7-build.326
emi-1.0.27+1.19.2+forge

**Comment by emilyploszaj** [comment]
This is EMI's end but is a touch annoying to resolve, I'd like to get it done soon though.

**Comment by emilyploszaj** [comment]
This should be fixed in 1.1.0

**Comment by Phoupraw** [comment]
It isn't fixed in 1.1.4+1.20.1+forge.
Mod list: [latest.log](https://github.com/emilyploszaj/emi/files/14894672/latest.log)

**Comment by Phoupraw** [comment]
@aaronhowser1 I build a version which fixed this bug (at least in my test).
[emi-1.1.4-SNAPSHOT+1.20.1+forge.zip](https://github.com/emilyploszaj/emi/files/14971472/emi-1.1.4-SNAPSHOT%2B1.20.1%2Bforge.zip)
Because github doesn't allow directly uploading jar file, so I changed its extension. If you want to use it as mod, you have to change its extension back to jar.

**Comment by emilyploszaj** [comment]
Please don't upload untrustworthy binaries in an attempt to skirt github's policies @Phoupraw, if you have a proper fix for this you can PR it, if you have more details on why it is not functioning correctly you can provide them
