### ISSUE TITLE
[Suggestion] Add support of curios inventories for EMI crafting detection.

### ISSUE THREAD

**Issue by PlayfulPiano** [emilyploszaj/emi#376]
Should be self explanatory, basically allowing support for how many resources you have remaining until making a specific craft, and detecting any resources inside inventories from curios (main situation would probably be backpacks) to include their totals as well.

**Comment by emilyploszaj** [comment]
Unfortunately it'd be completely unviable for quick crafting, you'd click craft and it'd just fail because your items are in your backpack, and it's be quite complex by itself to even count all the items, so I think this is both too difficult to add and a bit of an antifeature with how things currently are.
