### ISSUE TITLE
Move key binds to options.txt

### ISSUE THREAD

**Issue by kirjorjos** [emilyploszaj/emi#423]
As it stands, most launchers reset the key binds to default when a pack is updated, and we have to open a separate menu from where nearly every other mod puts their key binds to set the key binds for EMI.  Putting the key binds in options.txt would both persist user-defined key binds between pack updates and allow showing the key binds in the normal options > controls where most, if not all, other mos put their key binds.

**Comment by emilyploszaj** [comment]
EMI's keybinds can't be represented by minecraft, which does not support multiple binds with the same key, multiple keys for the same bind, modifier keys like control or shift, and additionally would make EMI unable to have global config for keybinds. The issue you're running into is caused by your modpack author.
