### ISSUE TITLE
oreDict selection will be reset when you quit a world in recipe tree

### ISSUE THREAD

**Issue by humonia-sys** [emilyploszaj/emi#463]

**Comment by emilyploszaj** [comment]
This issue is a bit unclear, and for the record, oreDict or the ore dictionary has not existed for over 6 years at this point, so I'm assuming you're talking about tags, but generally the recipe tree is not currently able to save between sessions. If you want to save your defaulted recipes, you'll have to default the tag resolutions.

**Comment by humonia-sys** [comment]
> This issue is a bit unclear, and for the record, oreDict or the ore dictionary has not existed for over 6 years at this point, so I'm assuming you're talking about tags, but generally the recipe tree is not currently able to save between sessions. If you want to save your defaulted recipes, you'll have to default the tag resolutions.

Yes I'm talking about tags, and when I use ctrl+left click to default a tag selection, it will just forget what I select when the game restart
