### ISSUE TITLE
[Feature] Autohiding, REI Style

### ISSUE THREAD

**Issue by ThePansmith** [emilyploszaj/emi#466]
A nice aspect about REI is that it will autohide items that have zero recipe entries. Having that for EMI would be a nice timesaver for packdeving.

**Comment by emilyploszaj** [comment]
EMI historically has had way more problems not showing items that should be visible rather than showing items that shouldn't be visible, so I don't think this would be desirable, and would be odd to have as a config option (as EMI supports global config overloading). I sympathize with the work required, but from what I can tell results will overall be better if done manually using EMI's options for item disabling and regex based matching.
