### ISSUE TITLE
Invisible ingredients in some recipes

### ISSUE THREAD

**Issue by CestQuoiUnPseudo** [emilyploszaj/emi#534]
Playing Monifactory Alpha 0.2.4, which is using EMI 1.1.6 1.20.1 forge. I've been seeing the problem on versions of Moni that uses EMI 1.1.6, but not in alpha 0.2.2, when it used EMI 1.1.4.

Here's a copy of the issue as reported in [ThePansmith/Monifactory](https://github.com/ThePansmith/Monifactory/issues/178):

> ![image](https://github.com/emilyploszaj/emi/assets/96011112/1386fc5c-1da4-4a80-8850-08036e50fcd1)
> I first saw it on this recipe
However the usual recipe work: glass + oxygen. Dunno if it's just my install
I also saw the same "invisible glass" problem on other recipes.
> ![image](https://github.com/emilyploszaj/emi/assets/96011112/c77980f6-e9d8-43f0-b470-493626945540)
> Centrifuging recipe for SiO2, MgO, CaO, Gold, Al2O3 and Tantalite
> ![image](https://github.com/emilyploszaj/emi/assets/96011112/3ce2052f-9970-4442-a574-4943f81724e1)
> Drilling fluid recipe. No other ways to make it, could be a game-breaking problem.
> ![image](https://github.com/emilyploszaj/emi/assets/96011112/b311aaa7-f4b8-4a47-bb91-c1adc5e88015)
> Ore washer, Impure pile of Salt into Salt
>Most Ore Washer recipes actually. Maybe it's a special brand of water?

Pansmith (lead Monifactory dev) answered that those weren't custom recipes and those were either GTCEu or EMI issues. I've been seeing a problem in the newest version of EMI and i'm assuming the problem might be with this mod.

Please let me know if you need more information

**Comment by emilyploszaj** [comment]
GT is invasive and modifies EMI in ways where I am unable to debug this issue, you'll have to rely on them to figure this out.

**Comment by CestQuoiUnPseudo** [comment]
Thanks for the answer, gonna check with them

**Comment by screret** [comment]
> GT is invasive and modifies EMI in ways where I am unable to debug this issue, you'll have to rely on them to figure this out.

we fixed that, remember?

**Comment by emilyploszaj** [comment]
I didn't know the extent of the changes, at least in this case EMI doesn't show these issues outside of gt recipes so I can't really debug it properly, it seems very likely it's on gt's end

**Comment by screret** [comment]
according to your tag manager, the minecraft:block/forge:glass tag is empty? this issue was introduced [here](https://github.com/emilyploszaj/emi/commit/a696783abd9bf21e29ae7cc74997e3cf125de9e8) which leads me to believe it isn't actually a GT issue.
[image](https://cdn.discordapp.com/attachments/984252821601919016/1244635008359206963/image.png?ex=6655d42e&is=665482ae&hm=8fb9cb714add77c26890b5d9dab504789b9d572030c0353baa79e23b7ad509c0&)

the loading system is checking for tag collisions and preferring the MC tag, but the `getRawValues` method *doesn't* do that, so it ends up returning an empty tag.
`EmiTags#reloadTags` calls `#consolodateTags` -> `#betterTag` which ends up picking the MC tag over the duplicate forge one.
