### ISSUE TITLE
Please add support for missing item previews for Integrated Terminals

### ISSUE THREAD

**Issue by PTALTS-LK** [emilyploszaj/emi#570]
![image](https://github.com/emilyploszaj/emi/assets/62936489/a50b806d-31de-454c-92c5-673c47cc624e)

**Comment by PTALTS-LK** [comment]
game version:1.20.1

**Comment by emilyploszaj** [comment]
This is something Integrated Terminals will have to add.

**Comment by PTALTS-LK** [comment]
> This is something Integrated Terminals will have to add.

What do you think about the fact that I was able to highlight missing items after I removed the jei?

**Comment by rubensworks** [comment]
Hi @emilyploszaj 👋 
This is the Integrated Terminals dev.

I've been looking into this, as based on my understanding, EMI should be able to handle mods that have JEI integration through the JEMI compat layer. Is that correct?

If so, I would assume things should be working then, given our [`TerminalStorageRecipeTransferHandler`](https://github.com/CyclopsMC/IntegratedTerminals-Compat/blob/master-1.21/src/main/java/org/cyclops/integratedterminalscompat/modcompat/jei/terminalstorage/TerminalStorageRecipeTransferHandler.java).
While I can see that the proper code is being called in my dev environment, and things are going through the JEMI layer, the missing items are not being highlighted.
This is while I am [passing the missing slots to the recipe transfer error](https://github.com/CyclopsMC/IntegratedTerminals-Compat/blob/master-1.21/src/main/java/org/cyclops/integratedterminalscompat/modcompat/jei/terminalstorage/TerminalStorageRecipeTransferHandler.java#L243).

Am I doing anything wrong on my end? Or am I misunderstanding how the JEMI layer works?

**Comment by emilyploszaj** [comment]
Hi, as I remember it, the info JEI actually exposes in the API that EMI can access doesn't properly allow EMI to display missing items or tooltips because JEI is designed in a way that has the recipe handler itself do rendering while EMI uses a widget system and its own tooltip backend so they can't easily be translated without some fragile hackery. The solution for "proper integration" would be native EMI compat, but integrated terminals should still remain functional (sans missing slot display) with just JEI compat. Sorry for the circumstances.

**Comment by rubensworks** [comment]
Ok, thanks for the details @emilyploszaj. I'll have a look to see what is possible.
