### ISSUE TITLE
[Feature Request] Ability to change the search bar position 

### ISSUE THREAD

**Issue by olo3345** [emilyploszaj/emi#626]

**Comment by emilyploszaj** [comment]
This is already a config option.

**Comment by AnzhiZhang** [comment]
I cannot find it.

**Comment by Gildedter** [comment]
> This is already a config option.

I don't see it, I'm on NeoForge 1.21.1, help...

I tried looking under UI on the mod config but nothing says about the actual search bar position, there is one for the effects position but that's it

I'm also using the Configured mod on CurseForge to view the mods in game

**Comment by miss-programgamer** [comment]
Since the devs helpfully decided to close the issue without elaborating, here's how to find the setting; it's "Center Search Bar" under the "UI" group of EMI's settings screen:

<img width="1920" height="1050" alt="Image" src="https://github.com/user-attachments/assets/cde0f515-d8c7-4504-b03d-9b21b3c93b9e" />

It'll be set to "true" by default, but you can set it to "false" to put the search bar back where it belongs.
