### ISSUE TITLE
Why does emi use css for its config file?

### ISSUE THREAD

**Issue by Blayung** [emilyploszaj/emi#628]
Why

**Comment by emilyploszaj** [comment]
CSS is a completely usable language for config that works across EMI's loader and version agnostic goals, since EMI is running from 1.4.7 to Fabric, Quilt, and Neoforge, I cannot rely on any existing loader config APIs. My goal to also have a global config means I can't use differing languages for different distributions. CSS is additionally a language most every text editor that does syntax highlighting will have syntax highlighting for, which is much easier for a user to edit, unlike something conventional like JSON, which is non-straightforward and unstandardized in common usages, and "modern" config languages without editor support.

**Comment by Chalks** [comment]
> CSS is a completely usable language for config...

This is a genuinely incredible decision and I LOVE it. It would never have occurred to me to use CSS for config, and I've been a frontend engineer for over a decade now. I'm setting up a modpack for my family's minecraft server (now that I have kids who want to play) and your `.css` config amazed me so much I had to come find a way to talk about it. I didn't even realize it was a configuration file at first because I'm so unfamiliar with Minecraft modding I just assumed you were actually styling something! When I finally opened the file and realized what was actually happening and that it was actually valid CSS... I don't think I've ever been more pleased, bemused, and in awe.

I'm a fan. I've never seen this before and it's very clever.
