### ISSUE TITLE
Some items not shown in search if you select "Registered" index instead of "Creative Tab" [1.21 NeoForge]

### ISSUE THREAD

**Issue by GordonHollow** [emilyploszaj/emi#655]
There is a list of what's became hidden:

specified enchantment books became just one item "enchanted book", so no way to check max lvl of enchants or some modded recipe for making books

most of bee spawn eggs from productive bees

PS: if you select "creative tab" index all of that items shown, but whole item list is a big mess, where vanilla and modded items just mixed up weird ways. And not showing full vanilla item list first, and mods item lists in alphabetical modname order after vanilla. So "registered" provide better sorted item list, but instead some items missing.

**Comment by emilyploszaj** [comment]
This is the intended functioning of "Registered". I don't find it particularly useful, which is why it is not on by default. Minecraft doesn't, really, have a way to determine what "sub items" exist for an item, say, enchanted books. The only way you can determine this is by asking creative tabs, and thus the ordering will be based on the minecraft creative tabs, and how mods add to them. I'd like to add more options for the index and its sorting in the future.

**Comment by GordonHollow** [comment]
I see at least 2 variants to solve that

1) Just add alphabetical mod filtering to "Creative Tab" setting, so it's not a mess of vanilla and modded items

2) Take order of items from "Registered", but include all missing items from "Creative Tab". Cause this extras have no order in "registered" - just put them in the end of correspondent mod item list
