### ISSUE TITLE
[Feature request] Option to use decimal values instead of rounded up values in recipe tree

### ISSUE THREAD

**Issue by jam-jar-binks** [emilyploszaj/emi#698]
When viewing a recipe such as fences, the required amount of resources is rounded up to a integer. While useful for non production settings, it can be misleading when attempting to create large scale production for various resources, as it can lead to misinterpretation of the required resources for a given production line.

I suggest added a config or ingame toggle (off by default) that changes the displayed amount of items needed per crafting step to the unrounded (or rounded to nearest hundredth) decimal value. 

This would allow players who are not interested in this feature to play without impact, but would allow much cleaner optimization of crafting trees, and give a clear view into how a given resource scales, as well as allowing for simple calculation of chance based resources. (For example, 1 sand producing 0.25 clay on average)

Current version:
![image](https://github.com/user-attachments/assets/713dcd5a-796b-4632-9a2e-5f39b0dd43de)

Proposed version (with ingame toggle in bottom right):
![Screenshot 2024-09-13 114100](https://github.com/user-attachments/assets/3f9a904d-593f-4c8e-8108-550d5cc1a6a7)

**Comment by emilyploszaj** [comment]
EMI does not round numbers, it rounds *batches*. This is easy to see crafting 1 bowl, where EMI will say you need 3 planks, rather than "rounding up" to 1. Currently, if you want a fractional cost per batch, there is a tooltip on recipe outputs that will display this. Future adjustments to the recipe tree to have a toggle for this are tracked in general recipe tree improvement issues, so I'll close this one.
