### ISSUE TITLE
Crash while Loading EMI in World

### ISSUE THREAD

**Issue by mxnmnm** [emilyploszaj/emi#735]
### Describe the bug, attach relevant log files, and describe what environment the issue occurs in
My EMI was taking a bit to load because of the large number of mods I'm running, so I waited for it to load then I crashed. I was looking in a crafting table before I crashed. I am running forge 47.3.6 and EMI 1.1.14. Here is the crash: https://gist.github.com/mxnmnm/207a3d50a1373e0ac032d632d42eef34

**Comment by emilyploszaj** [comment]
It is unclear which mod is causing this because the log is crashing on render thread, but some mod is initializing or drawing screens off of render thread causing a conmodex. Additionally, you have connector installed. I wish I could point you in the right direction but it is unclear from this log what is causing this errant behavior. Sorry
